version: 2.1
orbs:
  node: circleci/node@5.0.0
  aws-ecr: circleci/aws-ecr@7.3.0
  aws-eks: circleci/aws-eks@2.1.1
  kubernetes: circleci/kubernetes@1.3
jobs:
  test:
    executor:
      name: node/default
      tag: '16.10'
    steps:
    - checkout
    - node/install-packages:
        pkg-manager: yarn
    - run:
        command: yarn lint
        name: Run Mocha tests
    - run:
        command: yarn format:check
        name: Run Mocha tests
    - run:
        command: yarn test
        name: Run Mocha tests
    - run:
        command: yarn test:cov
        name: Run Mocha tests
    - run:
        command: yarn test:e2e
        name: Run Mocha tests
    - store_artifacts:
        path: /tmp/test-results
        destination: raw-test-output
    - store_test_results:
        path: /tmp/test-results
  run-deployment:
    executor: eks/defaut
    parameters:
      cluster-name:
        description: |
          demo
        type: string
    steps:
      - checkout
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: demo
          install-kubectl: true
          aws-region: us-east-01
      - kubernetes/create-or-update-resource:
          resource-file-path: "deployment/deployment.yaml"
          get-rollout-status: true
          resource-name: deployment/a15-deployment
      - kubernetes/create-or-update-resource:
          resource-file-path: "deployment/svc.yaml"
workflows:
  node-tests:
    jobs:
    - test
    # Envs: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_REGION, AWS_ECR_ACCOUNT_URL
    - aws-ecr/build-and-push-image:
        repo: hello
        tag: "latest"
        dockerfile: Dockerfile
        path: .
        requires:
          - test
    - run-deployment:
        cluster-name: demo
        requires:
          - test
          - aws-ecr/build-and-push-image