apiVersion: v1
kind: Service
metadata:
  name: a15-prod-service
  namespace: production
spec:
  selector:
    app: a15
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
